insert into smart_solutions_app_servicepricelist (description, price, service_id) values ('Stiffness of unspecified hip, not elsewhere classified', 94231, 4);
insert into smart_solutions_app_servicepricelist (description, price, service_id) values ('Poisoning by glucocorticoids and synthetic analogues, accidental (unintentional)', 4005, 2);
insert into smart_solutions_app_servicepricelist (description, price, service_id) values ('Cutaneous follicle center lymphoma, extranodal and solid organ sites', 16789, 6);
insert into smart_solutions_app_servicepricelist (description, price, service_id) values ('Open bite of front wall of thorax without penetration into thoracic cavity', 94642, 4);
insert into smart_solutions_app_servicepricelist (description, price, service_id) values ('Poisoning by antipruritics, assault, initial encounter', 75009, 2);
insert into smart_solutions_app_servicepricelist (description, price, service_id) values ('Synovial hypertrophy, not elsewhere classified, left ankle and foot', 11243, 6);
insert into smart_solutions_app_servicepricelist (description, price, service_id) values ('Fracture of unspecified part of body of mandible, unspecified side, subsequent encounter for fracture with delayed healing', 92028, 3);
insert into smart_solutions_app_servicepricelist (description, price, service_id) values ('Contact with unspecified sharp object, undetermined intent', 70689, 10);
insert into smart_solutions_app_servicepricelist (description, price, service_id) values ('Displaced fracture of lateral condyle of right tibia, subsequent encounter for open fracture type I or II with nonunion', 64153, 5);
insert into smart_solutions_app_servicepricelist (description, price, service_id) values ('Injury of sciatic nerve at hip and thigh level', 37259, 2);
insert into smart_solutions_app_servicepricelist (description, price, service_id) values ('Other physeal fracture of lower end of right fibula, initial encounter for closed fracture', 73463, 9);
insert into smart_solutions_app_servicepricelist (description, price, service_id) values ('Spastic ectropion of right lower eyelid', 50235, 6);
insert into smart_solutions_app_servicepricelist (description, price, service_id) values ('Concussion without loss of consciousness', 48993, 1);
insert into smart_solutions_app_servicepricelist (description, price, service_id) values ('Displaced comminuted fracture of unspecified patella, subsequent encounter for closed fracture with delayed healing', 58737, 3);
insert into smart_solutions_app_servicepricelist (description, price, service_id) values ('Laceration of transverse colon, initial encounter', 12975, 8);
insert into smart_solutions_app_servicepricelist (description, price, service_id) values ('Striking against wall of swimming pool causing drowning and submersion, subsequent encounter', 88038, 1);
insert into smart_solutions_app_servicepricelist (description, price, service_id) values ('Complete loss of teeth, unspecified cause, class IV', 95172, 3);
insert into smart_solutions_app_servicepricelist (description, price, service_id) values ('Displaced fracture of proximal phalanx of unspecified thumb, initial encounter for open fracture', 73939, 2);
insert into smart_solutions_app_servicepricelist (description, price, service_id) values ('Contusion of lip', 58194, 7);
insert into smart_solutions_app_servicepricelist (description, price, service_id) values ('Personal history of malignant neoplasm of epididymis', 41361, 4);
insert into smart_solutions_app_servicepricelist (description, price, service_id) values ('Intermittent monocular esotropia', 22602, 5);
insert into smart_solutions_app_servicepricelist (description, price, service_id) values ('Burn of third degree of right knee, subsequent encounter', 61811, 8);
insert into smart_solutions_app_servicepricelist (description, price, service_id) values ('Nondisplaced transverse fracture of shaft of unspecified radius, subsequent encounter for closed fracture with malunion', 49439, 2);
insert into smart_solutions_app_servicepricelist (description, price, service_id) values ('Unspecified open wound, left lower leg, initial encounter', 25232, 8);
insert into smart_solutions_app_servicepricelist (description, price, service_id) values ('Other injury of other muscles, fascia and tendons at forearm level, unspecified arm, initial encounter', 76992, 1);
insert into smart_solutions_app_servicepricelist (description, price, service_id) values ('Osteolysis, unspecified thigh', 16253, 3);
insert into smart_solutions_app_servicepricelist (description, price, service_id) values ('Female genital mutilation Type III status', 5072, 7);
insert into smart_solutions_app_servicepricelist (description, price, service_id) values ('Other shoulder lesions, unspecified shoulder', 32055, 2);
insert into smart_solutions_app_servicepricelist (description, price, service_id) values ('Evans syndrome', 61457, 7);
insert into smart_solutions_app_servicepricelist (description, price, service_id) values ('Cardiac tamponade', 12442, 10);
insert into smart_solutions_app_servicepricelist (description, price, service_id) values ('Nondisplaced supracondylar fracture with intracondylar extension of lower end of unspecified femur, initial encounter for open fracture type I or II', 1307, 2);
insert into smart_solutions_app_servicepricelist (description, price, service_id) values ('Lung transplant infection', 64523, 5);
insert into smart_solutions_app_servicepricelist (description, price, service_id) values ('Unspecified fracture of unspecified thoracic vertebra, subsequent encounter for fracture with routine healing', 88339, 4);
insert into smart_solutions_app_servicepricelist (description, price, service_id) values ('Toxic effect of thallium, undetermined, sequela', 67023, 4);
insert into smart_solutions_app_servicepricelist (description, price, service_id) values ('Other brachial plexus birth injuries', 74868, 7);
insert into smart_solutions_app_servicepricelist (description, price, service_id) values ('Traumatic vasospastic syndrome, initial encounter', 42249, 4);
insert into smart_solutions_app_servicepricelist (description, price, service_id) values ('Burn of second degree of left axilla', 40586, 2);
insert into smart_solutions_app_servicepricelist (description, price, service_id) values ('Coma scale, best verbal response, confused conversation', 93430, 10);
insert into smart_solutions_app_servicepricelist (description, price, service_id) values ('Displaced articular fracture of head of left femur, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with malunion', 9058, 10);
insert into smart_solutions_app_servicepricelist (description, price, service_id) values ('Fracture of anterior wall of acetabulum', 30907, 10);
