insert into smart_solutions_app_service (title, description) values ('Konklux', 'Transfer Left Shoulder Muscle with Subcutaneous Tissue, Percutaneous Endoscopic Approach');
insert into smart_solutions_app_service (title, description) values ('Y-Solowarm', 'Drainage of Left Upper Leg Tendon, Open Approach, Diagnostic');
insert into smart_solutions_app_service (title, description) values ('Quo Lux', 'Supplement Thoracic Aorta, Ascending/Arch with Synthetic Substitute, Percutaneous Approach');
insert into smart_solutions_app_service (title, description) values ('Bamity', 'Fluoroscopy of Right Elbow using Other Contrast');
insert into smart_solutions_app_service (title, description) values ('Viva', 'Supplement Right Foot Artery with Synthetic Substitute, Percutaneous Endoscopic Approach');
insert into smart_solutions_app_service (title, description) values ('Fix San', 'Resection of Left Maxillary Sinus, Open Approach');
insert into smart_solutions_app_service (title, description) values ('Home Ing', 'Extirpation of Matter from Left Elbow Joint, Percutaneous Endoscopic Approach');
insert into smart_solutions_app_service (title, description) values ('Subin', 'Bypass Right Pulmonary Artery from Carotid with Zooplastic Tissue, Open Approach');
insert into smart_solutions_app_service (title, description) values ('Quo Lux', 'Excision of Left Pulmonary Vein, Percutaneous Approach, Diagnostic');
insert into smart_solutions_app_service (title, description) values ('Mat Lam Tam', 'Computerized Dynamic Posturography Assessment using Vestibular / Balance Equipment');
